
baseurl = "https://jeremypoole.ca" # Hostname (and path) to the root.
title = "Jeremy Poole" # Site title.
theme = "coder" # Set the theme
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters

    author = "Jeremy Poole" # Author's name.
    avatar = "/images/av.png" # Avatar url.
    info = "Front-end engineer, Node.js and Linux" # Author's job title or info.
    description = "Jeremy Poole is a freelance web developer, specializing in JavaScript, HTML and CSS. He is located in Vancouver, BC, Canada. His favourite front-end framework is Vue.js" # Site description.
    keywords = "web,developer,javascript,vancouver,vue.js" # Site keywords.

    #disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = ["/css/custom.css"]

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    logo = "/images/github.png"
    weight = 1
    url = "https://github.com/jeremy21212121/"
[[params.social]]
    name = "LinkedIn"
    logo = "/images/linkedin.png"
    weight = 2
    url = "https://www.linkedin.com/in/jeremy-poole-10041a10a/"
[[params.social]]
    name = "Triplebyte certificate"
    logo = "/images/triplebyte.png"
    weight = 3
    url = "https://triplebyte.com/certificate/bk2AWtG"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url = "/posts/"


# [avatar]
#    url = "/static/av.png" # Avatar url.
#    alt = "Artist's Rendering of Jeremy Poole"
